Repository milieuinfo/webcomponent-vl-ui-properties, pull requests merged in 2019-09, with the labels that each got.

#18 UIG-218
  vl-properties.src.js
Labels: maintenance

#19 Update link naar demo
  vl-properties.src.js
Labels: maintenance

#20 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#9 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#23 Update dependency vl-ui-titles to v1.0.12
  package-lock.json
  package.json
Labels: dependencies

#22 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#21 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#24 Update dependency vl-ui-core to v1.4.7
  package-lock.json
  package.json
Labels: dependencies

#25 Automatic commit via update script
  demo/demo.css
  package-lock.json
  style.css
Labels: maintenance

#27 Update and install latest util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance
