Repository milieuinfo/webcomponent-vl-ui-properties, pull requests merged in 2020-01, with the labels that each got.

#43 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.js
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
  wct.docker.conf.json
  wct.local.conf.json
Labels: maintenance

#38 Initiele opzet
  .mocharc.js
  bamboo-specs/bamboo.yml
  demo/demo.css
  index.js
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
  test/e2e/pages/vl-properties.page.js
  test/e2e/properties.test.js
  test/unit/vl-properties.test.html
  test/wct.docker.conf.json
  wct.docker.conf.json
  wct.local.conf.json
Labels: chore

#44 Update gitignore zodat de vl-properties component in git komt
  .gitignore
  test/e2e/components/vl-properties.js
Labels: bugfix

#47 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#45 Overbodig NPM release import scripts verwijderd
  package.json
Labels: maintenance

#46 Update vl-ui-util
  demo/demo.css
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#48 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#50 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance

#51 Update vl-ui-util
  package-lock.json
  package.json
Labels: chore

#52 Stijl van vl-ui-core toevoegen
  style.css
  style.scss
Labels: bug
